// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Security Hotspot", "S4792:Configuring loggers is security-sensitive", Justification = "Is already been controlled in the code")]
[assembly: SuppressMessage("Security Hotspot", "S4507:Make sure this debug feature is deactivated before delivering the code in production.", Justification = "Is already been controlled in the code")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1010:Opening square brackets should be spaced correctly", Justification = "For avoid error SA1003", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Infrastructure.Swagger.IdentityServerApiSecurityOperationFilter.Apply(Microsoft.OpenApi.Models.OpenApiOperation,Swashbuckle.AspNetCore.SwaggerGen.OperationFilterContext)")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1010:Opening square brackets should be spaced correctly", Justification = "For avoid error SA1003", Scope = "member", Target = "~F:GtMotive.Estimate.Microservice.Host.Infrastructure.Swagger.IdentityServerApiSecurityOperationFilter.OpenApiSecuritySchemesValues")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "ApiController have to be public", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.CustomersController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "ApiController have to be public", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.RentingsController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "ApiController have to be public", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.VehiclesController")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.VehiclesController.PostVehicle(GtMotive.Estimate.Microservice.ApplicationCore.Models.Dtos.VehicleDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.VehiclesController.PutVehicle(GtMotive.Estimate.Microservice.ApplicationCore.Models.Dtos.VehicleDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.VehiclesController")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.CustomersController.PostCustomer(GtMotive.Estimate.Microservice.ApplicationCore.Models.Dtos.CustomerDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.CustomersController.PutCustomer(GtMotive.Estimate.Microservice.ApplicationCore.Models.Dtos.CustomerDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.CustomersController")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.RentingsController.PostRenting(GtMotive.Estimate.Microservice.ApplicationCore.Models.Dtos.RentingDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Host.Controllers.RentingsController")]
[assembly: SuppressMessage("Style", "IDE0046:Convertir a expresión condicional", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Host.Controllers.RentingsController.PutRentingClose(System.Int32,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
