// <auto-generated />
using System;
using GtMotive.Estimate.Microservice.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GtMotive.Estimate.Microservice.Infrastructure.Migrations
{
    [DbContext(typeof(HexagonalDbContext))]
    partial class HexagonalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasFilter("[Document] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BirthDate = new DateTime(1993, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "44714852M",
                            DocumentType = 1,
                            LastName = "Garcia",
                            Name = "Pablo"
                        },
                        new
                        {
                            CustomerId = 2,
                            Document = "44693254L",
                            DocumentType = 2,
                            LastName = "Garcia",
                            Name = "Andrea"
                        },
                        new
                        {
                            CustomerId = 3,
                            Document = "44965142V",
                            DocumentType = 1,
                            LastName = "Garcia",
                            Name = "Pablo Antonio"
                        });
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<decimal>("PreciPerDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("YearsToNoActiveVehicle")
                        .HasColumnType("int");

                    b.HasKey("ParameterId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            ParameterId = 1,
                            PreciPerDay = 40m,
                            YearsToNoActiveVehicle = 5
                        });
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Renting", b =>
                {
                    b.Property<int>("RentingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentingId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("RentingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentings");

                    b.HasData(
                        new
                        {
                            RentingId = 1,
                            CustomerId = 1,
                            DateEnd = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 240.0,
                            VehicleId = 1
                        },
                        new
                        {
                            RentingId = 2,
                            CustomerId = 2,
                            DateEnd = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80.0,
                            VehicleId = 2
                        },
                        new
                        {
                            RentingId = 3,
                            CustomerId = 3,
                            DateEnd = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 160.0,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AdquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<string>("NumberId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VehicleId");

                    b.HasIndex("NumberId")
                        .IsUnique()
                        .HasFilter("[NumberId] IS NOT NULL");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Active = true,
                            AdquisitionDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = 2,
                            Doors = 3,
                            NumberId = "3729-FDS"
                        },
                        new
                        {
                            VehicleId = 2,
                            Active = true,
                            AdquisitionDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = 3,
                            Doors = 5,
                            NumberId = "0445-BCV"
                        },
                        new
                        {
                            VehicleId = 3,
                            Active = true,
                            AdquisitionDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = 1,
                            Doors = 5,
                            NumberId = "6647-CSM"
                        });
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Renting", b =>
                {
                    b.HasOne("GtMotive.Estimate.Microservice.Domain.Models.Customer", "Customer")
                        .WithMany("Rentings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GtMotive.Estimate.Microservice.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("Rentings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Customer", b =>
                {
                    b.Navigation("Rentings");
                });

            modelBuilder.Entity("GtMotive.Estimate.Microservice.Domain.Models.Vehicle", b =>
                {
                    b.Navigation("Rentings");
                });
#pragma warning restore 612, 618
        }
    }
}
