// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "For avoid xUnit1027.", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.InfrastructureTests.Infrastructure.TestServerCollectionFixture")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Test", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.CustomerRepositoryTest")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Test", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.InfrastructureTests.DataTest.Data")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Init instances", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.DataTest.Data.GetCustomers~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Customer}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Init instances", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.DataTest.Data.GetVehicles~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Vehicle}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Init instances", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.DataTest.Data.GetRentings~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Renting}")]
[assembly: SuppressMessage("Design", "CA1024:Use properties where appropriate", Justification = "Parameter", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.DataTest.Data.GetParameter~GtMotive.Estimate.Microservice.Domain.Models.Parameter")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Using", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "DatabaseInMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "Using", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Call async methods when in an async method", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "DatabaseMemory", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
