// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "For avoid xUnit1027.", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.FunctionalTests.Infrastructure.CompositionRootCollectionFixture")]
[assembly: SuppressMessage("Style", "IDE0063:Use la instrucción \"using\" simple", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.Infrastructure.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Maintainability", "CA1515:Considere la posibilidad de hacer que los tipos públicos sean internos", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.FunctionalTests.DataTest.Data")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.DataTest.Data.GetCustomers~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Customer}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.DataTest.Data.GetVehicles~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Vehicle}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.DataTest.Data.GetRentings~System.Collections.Generic.IList{GtMotive.Estimate.Microservice.Domain.Models.Renting}")]
[assembly: SuppressMessage("Style", "IDE0063:Use la instrucción \"using\" simple", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1024:Usar propiedades donde corresponda", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.DataTest.Data.GetParameter~GtMotive.Estimate.Microservice.Domain.Models.Parameter")]
[assembly: SuppressMessage("Style", "IDE0063:Use la instrucción \"using\" simple", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Llame a métodos asincrónicos cuando esté en un método asincrónico", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.Infrastructure.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.FunctionalTests.Infrastructure.Repositories.CustomerRepositoryTest.GetCustomerByIdShouldReturnCustomerWhenCustomerExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Llame a métodos asincrónicos cuando esté en un método asincrónico", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.RentingRepositoryTest.GetRentingByIdShouldReturnVehiclesWhenVehiclesEmpty~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1849:Llame a métodos asincrónicos cuando esté en un método asincrónico", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.InfrastructureTests.Repositories.VehicleRepositoryTest.GetVehiclesShouldReturnVehiclesWhenVehiclesExists~System.Threading.Tasks.Task")]
